import shirtRed from '/image/shirt-red.png';

export const productData = [
  {
    name: 'Baju Sport Merah',
    price: 120000,
    category: 'Baju',
    stock: 40,
    image: shirtRed,
  },
  {
    name: 'Celana Jeans Biru',
    price: 250000,
    category: 'Celana',
    stock: 30,
    image: shirtRed,
  },
  {
    name: 'Sepatu Lari Putih',
    price: 300000,
    category: 'Sepatu',
    stock: 20,
    image: shirtRed,
  },
  {
    name: 'Jaket Kulit Hitam',
    price: 450000,
    category: 'Jaket',
    stock: 15,
    image: shirtRed,
  },
  {
    name: 'Topi Baseball Abu-Abu',
    price: 75000,
    category: 'Aksesoris',
    stock: 60,
    image: shirtRed,
  },
  {
    name: 'Kaos Kaki Warna-warni',
    price: 25000,
    category: 'Aksesoris',
    stock: 100,
    image: shirtRed,
  },
  {
    name: 'Kemeja Batik',
    price: 180000,
    category: 'Baju',
    stock: 25,
    image: shirtRed,
  },
  {
    name: 'Celana Pendek Santai',
    price: 90000,
    category: 'Celana',
    stock: 50,
    image: shirtRed,
  },
  {
    name: 'Sweater Rajut Coklat',
    price: 200000,
    category: 'Sweater',
    stock: 35,
    image: shirtRed,
  },
  {
    name: 'Tas Punggung Hitam',
    price: 350000,
    category: 'Tas',
    stock: 10,
    image: shirtRed,
  },
  {
    name: 'Kacamata Hitam Stylish',
    price: 150000,
    category: 'Aksesoris',
    stock: 45,
    image: shirtRed,
  },
  {
    name: 'Kaus Polos Putih',
    price: 50000,
    category: 'Baju',
    stock: 80,
    image: shirtRed,
  },
  {
    name: 'Ransel Travel Besar',
    price: 400000,
    category: 'Tas',
    stock: 8,
    image: shirtRed,
  },
  {
    name: 'Cincin Perak',
    price: 120000,
    category: 'Perhiasan',
    stock: 25,
    image: shirtRed,
  },
  {
    name: 'Dompet Kulit Pria',
    price: 180000,
    category: 'Aksesoris',
    stock: 50,
    image: shirtRed,
  },
  {
    name: 'Baju Tidur Wanita',
    price: 95000,
    category: 'Baju',
    stock: 65,
    image: shirtRed,
  },
  {
    name: 'Kursi Lipat Outdoor',
    price: 200000,
    category: 'Perlengkapan',
    stock: 12,
    image: shirtRed,
  },
  {
    name: 'Jam Tangan Digital',
    price: 300000,
    category: 'Aksesoris',
    stock: 30,
    image: shirtRed,
  },
  {
    name: 'Kopi Arabica Premium',
    price: 120000,
    category: 'Makanan & Minuman',
    stock: 100,
    image: shirtRed,
  },
  {
    name: 'Lampu Meja Belajar LED',
    price: 75000,
    category: 'Elektronik',
    stock: 40,
    image: shirtRed,
  },
];
